defaultPortal: Tomma
portals:
  - name: Tomma
    portalId: 24245974
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLDwobPLMRIRAA0AQAAA4G0DQAJYAgEAAPgY1u3HCyCJ9KABKO7pDDIU_7409BhdNZ8vxaejyR5DRN_Y6Cg6OAAABEEAAAB4AAAAAAAAAAAAgAAAAAAABAAAwAcAjvAxPGBQBgBEAGBA_BgGABAgAwAAAAAAPP4DQhSIA-zj3UH-KdlUqGUCTwK0XS63dUoDbmExUgBaAA
        expiresAt: '2023-12-29T16:29:09.062Z'
    personalAccessKey: >-
      CiRlMzNkNzRiOS02ODYyLTQyYmItODM3YS1kYzVkZjMzMjk2MWEQ1u3HCxiJ9KABKhkABeaRgvwwiZ96Ch-kgR1W8AmdZMg9l6v7SgNuYTE
    sandboxAccountType: null
    parentAccountId: null
