defaultPortal: Tomma
portals:
  - name: Tomma
    portalId: 24245974
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CPTgoODKMRIRAA0AQAAA4G0DQAJYAgEAAPgY1u3HCyCJ9KABKO7pDDIUtaIp2KKbc_TRxT5JcUHxClPRsRQ6OAAABEEAAAB4AAAAAAAAAAAAgAAAAAAABAAAwAcAjvAxPGBQBgBEAGBA_BgGABAgAwAAAAAAPP4DQhQj4DIxTYY43zJ46k8_Lz4EbNfS0UoDbmExUgBaAA
        expiresAt: '2023-12-27T16:07:47.083Z'
    personalAccessKey: >-
      CiQ3NzZiY2I1MC0wZmU0LTRkODQtODM3Ny1iMjY3ZGZkYTJmNTQQ1u3HCxiJ9KABKhkABeaRggcUhgvtdaqss-G2FSsWUL6dmY1dSgNuYTE
    sandboxAccountType: null
    parentAccountId: null
