defaultPortal: Tomma
portals:
  - name: Tomma
    portalId: 24245974
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJu4063LMRIRAA0AQAAA4G0DQAJYAgEAAPgY1u3HCyCJ9KABKO7pDDIUTmWZT2eRThA_rQjbfwFRThstpj86OAAABEEAAAB4AAAAAAAAAAAAgAAAAAAABAAAwAcAjvAxPGBQBgBEAGBA_BgGABAgAwAAAAAAPP4DQhTHQkmdu5zK-78I29qBYOgGSTB_j0oDbmExUgBaAA
        expiresAt: '2023-12-29T13:12:58.167Z'
    personalAccessKey: >-
      CiQxN2JmYzUwMi0wMWFiLTRkOTItOWNkMC03YTJjMjhmOTQzOTAQ1u3HCxiJ9KABKhkABeaRgqKf9fQwj7TGAjlLWuJbzyfi2r-gSgNuYTE
    sandboxAccountType: null
    parentAccountId: null
